#!/bin/sh

if [ $1 == 'mirror' ]; then
kubeadm init --image-repository registry.aliyuncs.com/google_containers
else
kubeadm init
fi

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config

kubectl apply --filename https://git.io/weave-kube-1.6
systemctl enable kubelet && systemctl restart kubelet